"""Rendering and inspection of images generated by project programs."""

from __future__ import annotations

import base64
import binascii
from dataclasses import dataclass
import hashlib
from pathlib import Path
import re
import struct
import tempfile
from xml.etree import ElementTree

from .commands import CommandRunner
from .config import BuildConfig
from .errors import BuildError


@dataclass(frozen=True, slots=True)
class ImageDimensions:
    width: int
    height: int


@dataclass(frozen=True, slots=True)
class GeneratedImageInfo:
    width: int
    vector: bool


def png_dimensions(data: bytes) -> ImageDimensions | None:
    if len(data) < 24 or data[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    width, height = struct.unpack(">II", data[16:24])
    if width <= 0 or height <= 0:
        return None
    return ImageDimensions(width, height)


def jpeg_dimensions(data: bytes) -> ImageDimensions | None:
    """Read JPEG dimensions without a third-party imaging dependency."""

    if len(data) < 4 or data[:2] != b"\xff\xd8":
        return None
    position = 2
    while position + 4 <= len(data):
        if data[position] != 0xFF:
            position += 1
            continue
        marker = data[position + 1]
        position += 2
        if marker in {0xD8, 0xD9}:
            continue
        if position + 2 > len(data):
            break
        length = int.from_bytes(data[position : position + 2], "big")
        if length < 2 or position + length > len(data):
            break
        if marker in {
            0xC0,
            0xC1,
            0xC2,
            0xC3,
            0xC5,
            0xC6,
            0xC7,
            0xC9,
            0xCA,
            0xCB,
            0xCD,
            0xCE,
            0xCF,
        } and length >= 7:
            height = int.from_bytes(data[position + 3 : position + 5], "big")
            width = int.from_bytes(data[position + 5 : position + 7], "big")
            if width > 0 and height > 0:
                return ImageDimensions(width, height)
        position += length
    return None


def svg_dimensions(text: str) -> tuple[float, float] | None:
    try:
        root = ElementTree.fromstring(text)
    except ElementTree.ParseError:
        return None
    view_box = root.attrib.get("viewBox")
    if view_box:
        values = re.split(r"[\s,]+", view_box.strip())
        if len(values) == 4:
            try:
                width, height = float(values[2]), float(values[3])
            except ValueError:
                return None
            if width > 0 and height > 0:
                return width, height
    return None


class TikzRenderer:
    """Compile TikZ with XeLaTeX and render it as high-resolution PNG."""

    def __init__(self, config: BuildConfig, runner: CommandRunner) -> None:
        self.config = config
        self.runner = runner

    def render(self, tikz_source: str, source: Path) -> Path:
        paths = self.config.paths
        relative_source = (
            source.resolve().relative_to(paths.project_root).as_posix()
        )
        xelatex = self.runner.require(self.config.tools.xelatex, "编译 TikZ")
        ghostscript = self.runner.require(
            self.config.tools.ghostscript, "生成 TikZ PNG"
        )
        wrapper_source = self._wrapper(tikz_source)
        output_identity = "\0".join(
            (
                relative_source,
                wrapper_source,
                str(self.config.images.tikz_raster_dpi),
                str(self.config.images.tikz_min_raster_width),
                str(self.config.images.tikz_max_raster_dpi),
            )
        )
        digest = hashlib.sha256(
            output_identity.encode("utf-8")
        ).hexdigest()[:20]

        filename = f"tikz-{digest}.png"
        destination = paths.staged_source_dir / "_tikz" / filename
        destination.parent.mkdir(parents=True, exist_ok=True)
        paths.tikz_work_dir.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(
            prefix=f"tikz-{digest}-", dir=paths.tikz_work_dir
        ) as temporary:
            work_dir = Path(temporary)
            wrapper = work_dir / "picture.tex"
            wrapper.write_text(wrapper_source, encoding="utf-8")
            self._compile_xelatex(xelatex, wrapper, work_dir)
            self._render_png(
                ghostscript,
                work_dir / "picture.pdf",
                destination,
                work_dir,
            )
        return Path("_tikz") / filename

    def _wrapper(self, tikz_source: str) -> str:
        border = self.config.images.tikz_border_points
        return "\n".join(
            [
                rf"\documentclass[tikz,border={border:g}pt]{{standalone}}",
                r"\usepackage[UTF8,fontset=fandol]{ctex}",
                r"\usepackage{amsmath,amssymb,mathtools}",
                r"\usepackage{tikz}",
                (
                    r"\usetikzlibrary{positioning,fit,calc,arrows.meta,"
                    r"shapes.geometric,shapes.misc,3d,matrix,"
                    r"decorations.pathreplacing}"
                ),
                r"\usepackage{pgfplots}",
                r"\usepgfplotslibrary{groupplots}",
                r"\pgfplotsset{compat=1.18}",
                r"\begin{document}",
                tikz_source.strip(),
                r"\end{document}",
                "",
            ]
        )

    def _compile_xelatex(
        self,
        executable: str,
        wrapper: Path,
        cwd: Path,
    ) -> None:
        command = [
            executable,
            "-interaction=nonstopmode",
            "-halt-on-error",
            "-no-shell-escape",
        ]
        command.append(wrapper.name)
        self.runner.run(command, cwd=cwd)
        expected = cwd / "picture.pdf"
        if not expected.is_file():
            raise BuildError(f"XeLaTeX 未生成预期文件：{expected.name}")

    def _render_png(
        self, executable: str, pdf: Path, output: Path, cwd: Path
    ) -> None:
        dpi = self.config.images.tikz_raster_dpi
        while True:
            self.runner.run(
                [
                    executable,
                    "-q",
                    "-dSAFER",
                    "-dBATCH",
                    "-dNOPAUSE",
                    "-dUseCropBox",
                    "-sDEVICE=pngalpha",
                    f"-r{dpi}",
                    "-dTextAlphaBits=4",
                    "-dGraphicsAlphaBits=4",
                    f"-sOutputFile={output}",
                    str(pdf),
                ],
                cwd=cwd,
                quiet=True,
            )
            dimensions = png_dimensions(output.read_bytes())
            if dimensions is None:
                raise BuildError(f"Ghostscript 生成的 PNG 无效：{output}")
            minimum = self.config.images.tikz_min_raster_width
            if dimensions.width >= minimum:
                break
            next_dpi = min(
                self.config.images.tikz_max_raster_dpi,
                max(dpi + 1, round(dpi * minimum / dimensions.width)),
            )
            if next_dpi <= dpi:
                raise BuildError(
                    f"TikZ PNG 宽度仅 {dimensions.width}px，未达到 {minimum}px"
                )
            dpi = next_dpi

def inspect_data_image(mime: str, encoded: str, source: str) -> GeneratedImageInfo:
    """Inspect one Base64 data image embedded in a computation result."""

    try:
        data = base64.b64decode(re.sub(r"\s+", "", encoded), validate=True)
    except (ValueError, binascii.Error) as error:
        raise BuildError(f"嵌入图片 Base64 无效：{source}") from error
    normalized = mime.lower().removeprefix("image/")
    if normalized not in {"png", "jpeg", "jpg", "svg+xml", "svg"}:
        raise BuildError(f"不支持的嵌入图片格式 {mime!r}：{source}")
    dimensions: ImageDimensions | None = None
    vector = normalized in {"svg+xml", "svg"}
    if normalized == "png":
        dimensions = png_dimensions(data)
    elif normalized in {"jpeg", "jpg"}:
        dimensions = jpeg_dimensions(data)
    elif vector:
        view_box = svg_dimensions(data.decode("utf-8", errors="replace"))
        if view_box:
            dimensions = ImageDimensions(round(view_box[0]), round(view_box[1]))
    if dimensions is None:
        raise BuildError(f"嵌入图片内容与格式不匹配或尺寸无效：{source}")
    return GeneratedImageInfo(
        width=dimensions.width,
        vector=vector,
    )
