"""Rendering and inspection of images generated by project programs."""

from __future__ import annotations

import base64
import binascii
from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import struct
import tempfile
from typing import Any
from xml.etree import ElementTree

from .commands import CommandRunner
from .config import BuildConfig
from .errors import BuildError


TIKZ_RENDERER_SCHEMA = "tikz-renderer-v4"


@dataclass(frozen=True, slots=True)
class ImageDimensions:
    width: int
    height: int

    @property
    def aspect_ratio(self) -> float:
        return self.width / self.height


@dataclass(frozen=True, slots=True)
class GeneratedImageInfo:
    source: str
    format: str
    width: int | None
    height: int | None
    vector: bool
    byte_size: int

    def as_dict(self) -> dict[str, Any]:
        return {
            "source": self.source,
            "format": self.format,
            "width": self.width,
            "height": self.height,
            "vector": self.vector,
            "byte_size": self.byte_size,
        }


def png_dimensions(data: bytes) -> ImageDimensions | None:
    if len(data) < 24 or data[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    width, height = struct.unpack(">II", data[16:24])
    if width <= 0 or height <= 0:
        return None
    return ImageDimensions(width, height)


def jpeg_dimensions(data: bytes) -> ImageDimensions | None:
    """Read JPEG dimensions without a third-party imaging dependency."""

    if len(data) < 4 or data[:2] != b"\xff\xd8":
        return None
    position = 2
    while position + 4 <= len(data):
        if data[position] != 0xFF:
            position += 1
            continue
        marker = data[position + 1]
        position += 2
        if marker in {0xD8, 0xD9}:
            continue
        if position + 2 > len(data):
            break
        length = int.from_bytes(data[position : position + 2], "big")
        if length < 2 or position + length > len(data):
            break
        if marker in {
            0xC0,
            0xC1,
            0xC2,
            0xC3,
            0xC5,
            0xC6,
            0xC7,
            0xC9,
            0xCA,
            0xCB,
            0xCD,
            0xCE,
            0xCF,
        } and length >= 7:
            height = int.from_bytes(data[position + 3 : position + 5], "big")
            width = int.from_bytes(data[position + 5 : position + 7], "big")
            if width > 0 and height > 0:
                return ImageDimensions(width, height)
        position += length
    return None


def svg_dimensions(text: str) -> tuple[float, float] | None:
    try:
        root = ElementTree.fromstring(text)
    except ElementTree.ParseError:
        return None
    view_box = root.attrib.get("viewBox")
    if view_box:
        values = re.split(r"[\s,]+", view_box.strip())
        if len(values) == 4:
            try:
                width, height = float(values[2]), float(values[3])
            except ValueError:
                return None
            if width > 0 and height > 0:
                return width, height
    return None


class TikzRenderer:
    """Compile TikZ to SVG, with an explicit high-DPI PNG fallback."""

    def __init__(self, config: BuildConfig, runner: CommandRunner) -> None:
        self.config = config
        self.runner = runner
        self._pdf_svg_support: bool | None = None
        self._reported_raster_fallback = False

    def render(self, tikz_source: str, source: Path) -> Path:
        paths = self.config.paths
        relative_source = source.resolve().relative_to(paths.project_root).as_posix()
        xelatex = self.runner.require(
            self.config.tools.xelatex, "编译 TikZ"
        )
        requested_format = self.config.images.tikz_format
        dvisvgm = shutil.which(self.config.tools.dvisvgm)
        ghostscript = shutil.which(self.config.tools.ghostscript)
        svg_available = bool(dvisvgm and self._supports_pdf_svg(dvisvgm))
        actual_format = (
            "svg"
            if requested_format in {"auto", "svg"} and svg_available
            else "png"
        )
        if (
            requested_format == "svg"
            and not svg_available
            and not self.config.images.tikz_png_fallback
        ):
            raise BuildError(
                "当前 dvisvgm 未启用 PDF/PS 后端，无法安全保留 TikZ 几何图元"
            )
        if (
            requested_format in {"auto", "svg"}
            and not svg_available
            and not self._reported_raster_fallback
        ):
            self.runner.warning(
                "当前 dvisvgm 未启用 PDF/PS 后端；TikZ 将使用高分辨率 PNG"
            )
            self._reported_raster_fallback = True
        renderer_versions = {
            "xelatex": self.runner.version(xelatex),
            "dvisvgm": self.runner.version(dvisvgm) if dvisvgm else None,
            "ghostscript": self.runner.version(ghostscript) if ghostscript else None,
        }
        cache_material = {
            "schema": TIKZ_RENDERER_SCHEMA,
            "source": relative_source,
            "tikz": tikz_source.strip(),
            "format": requested_format,
            "actual_format": actual_format,
            "quality": {
                "border_points": self.config.images.tikz_border_points,
                "raster_dpi": self.config.images.tikz_raster_dpi,
                "min_raster_width": self.config.images.tikz_min_raster_width,
                "max_raster_dpi": self.config.images.tikz_max_raster_dpi,
                "svg_precision": self.config.images.tikz_svg_precision,
                "text_as_paths": self.config.images.tikz_text_as_paths,
            },
            "versions": renderer_versions,
            "wrapper": self._wrapper(tikz_source),
        }
        digest = hashlib.sha256(
            json.dumps(
                cache_material,
                ensure_ascii=False,
                sort_keys=True,
                separators=(",", ":"),
            ).encode("utf-8")
        ).hexdigest()[:20]

        if actual_format == "svg":
            extension = ".svg"
        else:
            extension = ".png"
        if extension == ".png" and not ghostscript:
            raise BuildError("TikZ PNG 输出需要 Ghostscript（gs）")

        filename = f"tikz-{digest}{extension}"
        cached = paths.tikz_cache_dir / filename
        destination = paths.staged_source_dir / "_tikz" / filename
        destination.parent.mkdir(parents=True, exist_ok=True)
        cache_candidates = [cached]
        if actual_format == "svg" and self.config.images.tikz_png_fallback:
            # A source-specific SVG conversion can fail even when dvisvgm has
            # PDF support.  The fallback shares the complete cache key (source,
            # settings, wrapper, and tool versions) and differs only by suffix.
            # Checking it here avoids recompiling the same known fallback on
            # every build.
            cache_candidates.append(
                paths.tikz_cache_dir / f"tikz-{digest}.png"
            )
        reusable = next(
            (
                candidate
                for candidate in cache_candidates
                if candidate.is_file() and self._valid_cache(candidate)
            ),
            None,
        )
        if reusable is not None:
            cached = reusable
            filename = cached.name
            destination = paths.staged_source_dir / "_tikz" / filename
            shutil.copy2(cached, destination)
            return Path("_tikz") / filename

        paths.tikz_cache_dir.mkdir(parents=True, exist_ok=True)
        paths.tikz_work_dir.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(
            prefix=f"tikz-{digest}-", dir=paths.tikz_work_dir
        ) as temporary:
            work_dir = Path(temporary)
            wrapper = work_dir / "picture.tex"
            wrapper.write_text(self._wrapper(tikz_source), encoding="utf-8")
            rendered = work_dir / filename
            if extension == ".svg":
                self._compile_xelatex(xelatex, wrapper, work_dir)
                pdf = work_dir / "picture.pdf"
                try:
                    self._render_svg(dvisvgm or "", pdf, rendered, work_dir)
                except BuildError:
                    if not self.config.images.tikz_png_fallback or not ghostscript:
                        raise
                    self.runner.warning(
                        f"SVG 转换失败，改用 {self.config.images.tikz_raster_dpi} DPI PNG："
                        f"{relative_source}"
                    )
                    extension = ".png"
                    filename = f"tikz-{digest}{extension}"
                    cached = paths.tikz_cache_dir / filename
                    destination = paths.staged_source_dir / "_tikz" / filename
                    rendered = work_dir / filename
                    self._render_png(ghostscript, pdf, rendered, work_dir)
            else:
                self._compile_xelatex(xelatex, wrapper, work_dir)
                pdf = work_dir / "picture.pdf"
                self._render_png(ghostscript or "", pdf, rendered, work_dir)

            if not self._valid_cache(rendered):
                raise BuildError(f"TikZ 转换产物无效：{relative_source}")
            cache_temporary = cached.with_name(cached.name + ".incoming")
            shutil.copy2(rendered, cache_temporary)
            os.replace(cache_temporary, cached)
            shutil.copy2(cached, destination)
        return Path("_tikz") / filename

    def _wrapper(self, tikz_source: str) -> str:
        border = self.config.images.tikz_border_points
        return "\n".join(
            [
                rf"\documentclass[tikz,border={border:g}pt]{{standalone}}",
                r"\usepackage[UTF8,fontset=fandol]{ctex}",
                r"\usepackage{amsmath,amssymb,mathtools}",
                r"\usepackage{tikz}",
                (
                    r"\usetikzlibrary{positioning,fit,calc,arrows.meta,"
                    r"shapes.geometric,shapes.misc,3d,matrix,"
                    r"decorations.pathreplacing}"
                ),
                r"\usepackage{pgfplots}",
                r"\usepgfplotslibrary{groupplots}",
                r"\pgfplotsset{compat=1.18}",
                r"\begin{document}",
                tikz_source.strip(),
                r"\end{document}",
                "",
            ]
        )

    def _render_svg(
        self, executable: str, pdf: Path, output: Path, cwd: Path
    ) -> None:
        command = [
            executable,
            "--pdf",
            "--page=1",
            # The standalone PDF already has a tightly cropped page plus the
            # configured safety border.  Keeping its page box prevents arrow
            # heads and line caps from touching the SVG edge.
            "--bbox=papersize",
            f"--precision={self.config.images.tikz_svg_precision}",
            "--embed-bitmaps",
            "--optimize=all",
            f"--output={output}",
        ]
        if self.config.images.tikz_text_as_paths:
            command.append("--no-fonts")
        command.append(str(pdf))
        self.runner.run(command, cwd=cwd, quiet=True)

    def _compile_xelatex(
        self,
        executable: str,
        wrapper: Path,
        cwd: Path,
    ) -> None:
        command = [
            executable,
            "-interaction=nonstopmode",
            "-halt-on-error",
            "-no-shell-escape",
        ]
        command.append(wrapper.name)
        self.runner.run(command, cwd=cwd)
        expected = cwd / "picture.pdf"
        if not expected.is_file():
            raise BuildError(f"XeLaTeX 未生成预期文件：{expected.name}")

    def _supports_pdf_svg(self, executable: str) -> bool:
        """Detect whether dvisvgm can preserve PDF/PS drawing operations."""

        if self._pdf_svg_support is None:
            try:
                details = self.runner.run(
                    [executable, "--version=yes"],
                    cwd=self.config.paths.html_dir,
                    quiet=True,
                ).lower()
            except BuildError:
                details = ""
            self._pdf_svg_support = "mupdf:" in details or "ghostscript:" in details
        return self._pdf_svg_support

    def _render_png(
        self, executable: str, pdf: Path, output: Path, cwd: Path
    ) -> None:
        dpi = self.config.images.tikz_raster_dpi
        while True:
            self.runner.run(
                [
                    executable,
                    "-q",
                    "-dSAFER",
                    "-dBATCH",
                    "-dNOPAUSE",
                    "-dUseCropBox",
                    "-sDEVICE=pngalpha",
                    f"-r{dpi}",
                    "-dTextAlphaBits=4",
                    "-dGraphicsAlphaBits=4",
                    f"-sOutputFile={output}",
                    str(pdf),
                ],
                cwd=cwd,
                quiet=True,
            )
            dimensions = png_dimensions(output.read_bytes())
            if dimensions is None:
                raise BuildError(f"Ghostscript 生成的 PNG 无效：{output}")
            minimum = self.config.images.tikz_min_raster_width
            if dimensions.width >= minimum:
                break
            next_dpi = min(
                self.config.images.tikz_max_raster_dpi,
                max(dpi + 1, round(dpi * minimum / dimensions.width)),
            )
            if next_dpi <= dpi:
                raise BuildError(
                    f"TikZ PNG 宽度仅 {dimensions.width}px，未达到 {minimum}px"
                )
            dpi = next_dpi

    @staticmethod
    def _valid_cache(path: Path) -> bool:
        try:
            data = path.read_bytes()
        except OSError:
            return False
        if path.suffix == ".png":
            return png_dimensions(data) is not None
        if path.suffix == ".svg":
            return TikzRenderer._valid_svg(data.decode("utf-8", errors="replace"))
        return False

    @staticmethod
    def _valid_svg(source: str) -> bool:
        if svg_dimensions(source) is None:
            return False
        try:
            root = ElementTree.fromstring(source)
        except ElementTree.ParseError:
            return False
        if root.tag.rsplit("}", 1)[-1].lower() != "svg":
            return False
        forbidden = {"script", "foreignObject"}
        drawable = {
            "path",
            "rect",
            "circle",
            "ellipse",
            "line",
            "polyline",
            "polygon",
            "text",
            "image",
            "use",
        }
        has_drawable = False
        for node in root.iter():
            local_name = node.tag.rsplit("}", 1)[-1]
            if local_name in forbidden:
                return False
            if local_name in drawable:
                has_drawable = True
            for key, value in node.attrib.items():
                if (
                    key.rsplit("}", 1)[-1] == "href"
                    and value
                    and not value.startswith(("#", "data:"))
                ):
                    return False
        return has_drawable


def inspect_data_image(mime: str, encoded: str, source: str) -> GeneratedImageInfo:
    """Inspect one Base64 data image embedded in a computation result."""

    try:
        data = base64.b64decode(re.sub(r"\s+", "", encoded), validate=True)
    except (ValueError, binascii.Error) as error:
        raise BuildError(f"嵌入图片 Base64 无效：{source}") from error
    normalized = mime.lower().removeprefix("image/")
    if normalized not in {"png", "jpeg", "jpg", "svg+xml", "svg"}:
        raise BuildError(f"不支持的嵌入图片格式 {mime!r}：{source}")
    dimensions: ImageDimensions | None = None
    vector = normalized in {"svg+xml", "svg"}
    if normalized == "png":
        dimensions = png_dimensions(data)
    elif normalized in {"jpeg", "jpg"}:
        dimensions = jpeg_dimensions(data)
    elif vector:
        view_box = svg_dimensions(data.decode("utf-8", errors="replace"))
        if view_box:
            dimensions = ImageDimensions(round(view_box[0]), round(view_box[1]))
    if dimensions is None:
        raise BuildError(f"嵌入图片内容与格式不匹配或尺寸无效：{source}")
    return GeneratedImageInfo(
        source=source,
        format=normalized,
        width=dimensions.width if dimensions else None,
        height=dimensions.height if dimensions else None,
        vector=vector,
        byte_size=len(data),
    )
