"""Small, strict HTML and YAML rendering helpers.

The project intentionally avoids a template dependency.  These helpers cover
the narrow structures generated by the build while escaping text and
attributes by default.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from dataclasses import dataclass
import html
import json
from typing import Any

from .errors import BuildError


class Markup(str):
    """A string that has already been intentionally rendered as HTML."""


def text(value: object) -> Markup:
    return Markup(html.escape(str(value)))


def raw(value: str) -> Markup:
    return Markup(value)


def join(parts: Iterable[str], separator: str = "") -> Markup:
    return Markup(separator.join(str(part) for part in parts))


def element(
    name: str,
    content: str | Iterable[str] = "",
    *,
    attributes: Mapping[str, object | None] | None = None,
    void: bool = False,
) -> Markup:
    """Render one HTML element with escaped attribute values."""

    if not name.replace("-", "").isalnum():
        raise BuildError(f"非法 HTML 元素名：{name}")
    rendered_attributes: list[str] = []
    for key, value in (attributes or {}).items():
        if value is None or value is False:
            continue
        if not key.replace("-", "").replace(":", "").isalnum():
            raise BuildError(f"非法 HTML 属性名：{key}")
        if value is True:
            rendered_attributes.append(key)
        else:
            rendered_attributes.append(
                f'{key}="{html.escape(str(value), quote=True)}"'
            )
    opening = "<" + name
    if rendered_attributes:
        opening += " " + " ".join(rendered_attributes)
    opening += ">"
    if void:
        return Markup(opening)
    if isinstance(content, str):
        body = content
    else:
        body = "".join(str(part) for part in content)
    return Markup(f"{opening}{body}</{name}>")


@dataclass(frozen=True, slots=True)
class LiteralBlock:
    """A YAML literal block scalar."""

    value: str


class YamlEmitter:
    """Emit the JSON-compatible YAML subset used by Quarto configuration."""

    def dumps(self, value: Mapping[str, Any]) -> str:
        lines = self._mapping(value, 0)
        return "\n".join(lines) + "\n"

    def _mapping(self, value: Mapping[str, Any], indent: int) -> list[str]:
        lines: list[str] = []
        prefix = " " * indent
        for key, item in value.items():
            if not isinstance(key, str) or not key:
                raise BuildError("YAML 配置键必须是非空字符串")
            if isinstance(item, Mapping):
                lines.append(f"{prefix}{key}:")
                lines.extend(self._mapping(item, indent + 2))
            elif isinstance(item, list):
                lines.append(f"{prefix}{key}:")
                lines.extend(self._sequence(item, indent + 2))
            elif isinstance(item, LiteralBlock):
                lines.append(f"{prefix}{key}: |-")
                lines.extend(
                    " " * (indent + 2) + line
                    for line in item.value.splitlines()
                )
            else:
                lines.append(f"{prefix}{key}: {self._scalar(item)}")
        return lines

    def _sequence(self, value: list[Any], indent: int) -> list[str]:
        lines: list[str] = []
        prefix = " " * indent
        for item in value:
            if isinstance(item, Mapping):
                items = list(item.items())
                if not items:
                    lines.append(prefix + "- {}")
                    continue
                first_key, first_value = items[0]
                if isinstance(first_value, (Mapping, list, LiteralBlock)):
                    lines.append(prefix + "-")
                    lines.extend(self._mapping(item, indent + 2))
                else:
                    lines.append(
                        f"{prefix}- {first_key}: {self._scalar(first_value)}"
                    )
                    if len(items) > 1:
                        lines.extend(
                            self._mapping(dict(items[1:]), indent + 2)
                        )
            elif isinstance(item, list):
                lines.append(prefix + "-")
                lines.extend(self._sequence(item, indent + 2))
            else:
                lines.append(f"{prefix}- {self._scalar(item)}")
        return lines

    @staticmethod
    def _scalar(value: Any) -> str:
        if value is None:
            return "null"
        if value is True:
            return "true"
        if value is False:
            return "false"
        if isinstance(value, (int, float)):
            return str(value)
        return json.dumps(str(value), ensure_ascii=False)
